name: Deploy Site
on:
   push:
      branches: [ main ]

jobs:
   deploy:
       runs-on: ubuntu-latest
       
       steps:
         - name: Checkout
           uses: actions/checkout@master

     
         - name: Setup Node.js
           uses: actions/setup-node@v2.1.2
           with:
              node-version: 14.x
              
         - name: Cache node_modules
           uses: actions/cache@v2
           with:
              path: node_modules
              key: ${{ runner.os }}-node-modules
      
         - name: Install Dependencies
           run: |
               cd src
               npm install
         - name: Generate Site
           run: |
              cd src
              npm run generate
              
        
         - name: Deploy to GitHub Pages (in main repository)
           if: github.repository_owner == 'scratch-contributors'
           uses: peaceiris/actions-gh-pages@v3
           with:
              github_token: ${{secrets.GITHUB_TOKEN}}
              publish_dir: ./src/dist
              user_name: 'scratchcontributors-bot'
              user_email: 'scratchcontributors-bot@users.noreply.github.com'
              
         - name: Deploy to GitHub Pages (not in main repository)
           if: github.repository_owner != 'scratch-contributors'
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: ./src/dist
